name: publish-app

on:
  push:
    branches:
      - 'release/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: dotnet-setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: dotnet-build
        run: 'dotnet build SpectraProcessing.sln'
